### ISSUE TITLE
Execution failed for task ':react-native-apk-installer-n:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by antonioMerkulov** [nodece/react-native-apk-installer-n#2]
I've got the error, when I tried to build apk with this library:
```
RNApkInstallerNModule.java:6: error: package android.support.v4.content does not exist
import android.support.v4.content.FileProvider;
```

It is necessary to replace import in file RNApkInstallerNModule.java:6
`import android.support.v4.content.FileProvider;` -> `import androidx.core.content.FileProvider;`

Then it works fine.

**Comment by nodece** [comment]
@antonioMerkulov Hi guys,  please upgrade the `react-native-apk-installer-n` to latest version.
