### ISSUE TITLE
Failed to build in RN ^0.69.0

### ISSUE THREAD

**Issue by lfrallon** [nodece/react-native-apk-installer-n#9]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/home/myapp/node_modules/react-native-apk-installer-n/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-apk-installer-n'.
> Plugin with id 'maven' not found.

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-apk-installer-n'.
> compileSdkVersion is not specified. Please add it to build.gradle

**Comment by Edanmer** [comment]
Having the same issue, have you found any solution?

**Comment by lfrallon** [comment]
Haven't found a solution for this but instead, I use [rn-fetch-blob](https://yarnpkg.com/package/rn-fetch-blob) to download and install an apk.

**Comment by kabundege** [comment]
@lfrallon how did you manage to install an APK with that ?!

**Comment by lfrallon** [comment]
> @lfrallon how did you manage to install an APK with that ?!

The `rn-fetch-blob` is just my alternative module since I can't get `react-native-apk-installer-n` to work in my project. If you want to use `rn-fetch-blob` you can actually refer to their GitHub repo and there's an example that you can find through their README file on how you can set up and [Open Downloaded File with Intent](https://github.com/joltup/rn-fetch-blob#download-to-storage-directly). 

Note though that the current version release has some [issues](https://github.com/joltup/rn-fetch-blob/issues/183), but you can use the [`"rn-fetch-blob": "0.13.0-beta.2"`](https://github.com/joltup/rn-fetch-blob/issues/798#issuecomment-1218917753) that I have in my project and it is working fine.

Btw I'm currently using:

"react": "18.1.0",
"react-native": "^0.70.6",

**Comment by sam9010** [comment]
@Edanmer 
@lfrallon 
@kabundege 
do you have any solution for install automatic apk? i don't see any package like this

**Comment by sam9010** [comment]
I find a solution (who can not use this library for upper version react native)...
1- install this library https://www.npmjs.com/package/rn-fetch-blob for download Apk
2-  add permission for **REQUEST_INSTALL_PACKAGES** in manifest.
then when download finish you can install Apk with this 
3-
import RNFetchBlob from 'rn-fetch-blob';

`RNFetchBlob.android.actionViewIntent(
      resource.path(), //path where the file is downloaded
      "application/vnd.android.package-archive",
    )`

**Comment by lfrallon** [comment]
Consider using [react-native-blob-util](https://www.npmjs.com/package/react-native-blob-util) as `rn-fetch-blob` is not maintained, `react-native-blob-util` is also forked from `rn-fetch-blob` but it is currently maintained.
